Fix FAQ button
digitalservice4germany/steuerlotse pull request #20
Opened 2021-07-04 20:44 UTC by ramboldio

# Short Description
This is very nitty-gritty stuff. Having said that, currently, on the FAQ a pointer is shown in an area, even though, nothing happens when clicking (see image). I solved this by expanding the button and therefore the actually clickable area to the entire available space.

![image](https://user-images.githubusercontent.com/5238799/124399001-0acc1580-dd19-11eb-9a5a-11db566b4189.png)

# Changes
- it's fixed now

2021-07-05 12:09 UTC, frederike-ramin requested changes
First of all, thank you for submitting the pull request and the effort you put into this.
Great catch with the non-clickable area!

I have two comments that I'd love you to have another look at. Otherwise it looks great. 👍

2021-07-07 16:54 UTC, ramboldio commented on webapp/app/static/css/components.css
> +.accordion button.card-header{
removed.

2021-07-08 11:27 UTC, frederike-ramin approved these changes
Nice work and thanks for implementing the changes!
I'll merge this asap. First external PR, I hope you're proud. :D

2021-07-08 12:09 UTC, merged

2021-07-08 12:14 UTC, ramboldio commented
:D Nice, on that note:


first