STL-1490 | Added react component for session note step
digitalservice4germany/steuerlotse pull request #599
Opened 2022-01-19 17:08 UTC by VicCamp

# Short Description
- Short description of this pull request.
- Provide any additional context as needed and explain reasons behind your implementation choices.
- Add any links to tickets, specs, documentation, external resources, etc. that may be relevant.

# Changes
- What changes does this pull request introduce?
- Are there any additional changes (e. g. refactoring) that are part of this pull request?

# Feedback
- Which parts of the code would you like feedback on?
- Questions that are open are also good (e. g. "Do you see any tests missing for class x?")

# How to review this Pull Request
[Link to Confluence](https://digitalservice4germany.atlassian.net/wiki/spaces/STL/pages/117637157/Development+Process#Approve-or-comment) (internal)

2022-01-20 07:23 UTC, VicCamp commented
I forgot! We could actually remove the template basis/display_standard_with_list.html since it was only being used to the session note component, right?

2022-01-20 07:30 UTC, VicCamp commented
I would resolve the minor merge conflicts after PR has been reviewed and approved.

2022-01-20 16:05 UTC, SannyNguyenHung requested changes
Just some small changes and we are done here :partying_face:

2022-01-20 18:53 UTC, SannyNguyenHung commented
> I forgot! We could actually remove the template basis/display_standard_with_list.html since it was only being used to the session note component, right?

Should be okay :+1:

2022-01-21 10:17 UTC, SannyNguyenHung commented on webapp/app/forms/steps/unlock_code_revocation_steps.py
> -HEADER_TITLE = 'form.unlock-code-revocation.header-title'
This will not work because the babel script generation search for uses of `_()` or `_l()`...

2022-01-21 10:31 UTC, SannyNguyenHung approved these changes

2022-01-21 10:32 UTC, merged